- name: basics
  hosts: localhost # Define the hosts at the top level for all plays
  connection: local
  gather_facts: false # Skip gathering facts for speed
  tasks:
    - name: Print hello message and countdown
      ansible.builtin.debug:
        msg: |
          "Hello! Configuration and installation on this desktop is starting in..."

    # - name: Countdown timer (3, 2, 1)
    #   ansible.builtin.pause:
    #     seconds: 1
    #   register: countdown_result
    #   until: countdown_result is not failed
    #   retries: 3
    #   delay: 1

    # - name: Final countdown message
    #   ansible.builtin.debug:
    #     msg: "Starting installation now!"

- name: Install Nala
  become: true # Ensure we have root privileges to install Nala
  tasks:
    - name: Install Nala package
      ansible.builtin.apt:
        name: nala
        state: present
        update_cache: yes # Ensure apt cache is updated before installation

- name: Update packages using Nala
  become: true # Use root privileges to update packages
  tasks:
    - name: Update package list using Nala
      ansible.builtin.command:
        cmd: nala update -y

- name: Upgrade packages using Nala
  become: true # Use root privileges to upgrade packages
  tasks:
    - name: Upgrade packages using Nala
      ansible.builtin.command:
        cmd: nala upgrade -y
